(feat) enable testing in development
sixfeetup/scaf pull request #185
Opened 2024-03-04 20:33 UTC by sjlawson

I needed to be able to run pytest locally. Currently TDD on scaf project is broken because the Dockerfile skips the tests requirements file in development. It was an easy fix that I already implemented on my becks project. 

I also added `.idea/` to gitignore

2024-03-05 08:47 UTC, rochecompaan commented
Test requirements are installed if `DEVEL=yes.` Could you let me know why this is not enough?

2024-03-05 08:49 UTC, rochecompaan commented
You should be able to run tests with:
```
kubectl exec <django-pod-id> -- pytest
```
We should add a Makefile target for the above.

2024-03-05 16:39 UTC, sjlawson commented
> Test requirements are installed if `DEVEL=yes.` Could you let me know why this is not enough?

This does not seem to be the case... at least in the scaf installation I have.  Without `TEST=yes` it doesn't install the `requirements/test.txt` so Pytest and all it's requirements aren't installed in the django pod

2024-03-06 10:05 UTC, rochecompaan commented
Apologies, I misread the Dockerfile, we do need `TEST=yes`.

2024-03-06 10:06 UTC, rochecompaan requested changes
Can you please remove the git ignore for `.idea` since there is often value to share IDE project configuration. If teams really want to exclude that, they can add it to .gitignore in the generated project.

2024-04-11 06:36 UTC, rochecompaan commented
Testing in development was addressed in this PR: https://github.com/sixfeetup/scaf/pull/214

2024-04-11 06:36 UTC, closed without merging