feat: add automatic git remote configuration
sixfeetup/scaf pull request #336
Opened 2024-08-14 14:45 UTC by gfranxman

Added functionality to automatically configure git remote repositories to the scaf creation process.

This is done in the post_gen_project.py hook file using a new function called `configure_git_remote()`.  This function takes the repository URL built during the cookiecutter build out and initializes a new git repository in the new project directory.  It then sets the entered URL as the 'origin' remote.

Subsequently, removed the `git init .` statement from the scaf script since it now occurs in the `configure_git_remote()` function of the post_gen_project hook.

Also provided a detailed guide in README.md on how to test the cookiecutter portion of scaf.

2024-08-15 02:33 UTC, rochecompaan requested changes
Looks good!

Can we make the testing more reusable, please? Either in this PR or another.

2024-08-15 02:33 UTC, rochecompaan commented on README.md
> +```
This deserves a separate issue and PR where we work out the testing details in a more reusable way. For instance, we can have Makefile  target called `test` and `test-remote`:
```
BRANCH_NAME = $(shell git rev-parse --abbrev-ref HEAD)
BASE_REPO = https://github.com/sixfeetup/scaf.git
SCAF_ROOT = $(shell pwd)

test:
	echo ${BRANCH_NAME}
	rm -rf /tmp/scaf-test && \
	mkdir /tmp/scaf-test && \
	./scaf myproject -o /tmp/scaf-test --no-input .     # this does not currently work, but it should

test-remote:
	echo ${BRANCH_NAME}
	rm -rf /tmp/scaf-test && \
	mkdir /tmp/scaf-test && \
	cd /tmp/scaf-test && \
	cp ${SCAF_ROOT}/cookiecutter.json . && \
	${SCAF_ROOT}/scaf myproject \
		--no-input \
		--checkout ${BRANCH_NAME} ${BASE_REPO}
```

2024-08-15 02:33 UTC, rochecompaan commented on README.md
> +Create a test cookiecutter.yaml file with the following content:
We could just use the default `cookiecutter.json`, see my comment below.

2024-08-16 13:40 UTC, gfranxman commented
Made a ticket for turning the testing docs into code and makefile targets

2024-08-21 13:24 UTC, merged