docs: change readme structure
sixfeetup/scaf pull request #369
Opened 2024-09-06 23:04 UTC by hillairet

Fix #365 

The idea of this new structure is to have the repo's README route the reader to the right section for a given purpose. A reader should only need to go to one file linked from the README at a given time, e.g. when someone wants to set up their local environment, they don't care (yet) about deploying so these two are in two different files.

Also using emojis to make it less dry and easier to scan quickly.

I did only minor doc changes such as section levels and switching references to other files from code format to actual links. The rest of the text is unchanged, just moved.

2024-09-09 08:04 UTC, rochecompaan approved these changes

2024-10-11 06:35 UTC, rochecompaan requested changes

2024-10-11 06:35 UTC, rochecompaan commented on {{cookiecutter.project_slug}}/docs/deployment.md
> +Read [k8s/argocd/README.md](/k8s/argocd/README.md) for more details.
Please fix the link:
```suggestion
Use ArgoCD and Kubernetes to automate the deployment of your application to your infrastructure. ArgoCD monitors changes within your repository, promptly applying the relevant Kubernetes manifests. Read [bootstrap-cluster/README.md](/bootstrap-cluster/README.md) for more details.
```

2024-10-11 19:08 UTC, hillairet commented
@rochecompaan Merging to make sure we have this documentation for our newest project.

2024-10-11 19:08 UTC, merged