feat: added local registry support and improved setup
sixfeetup/scaf pull request #383
Opened 2024-09-18 00:30 UTC by daveoconnor

2024-09-18 00:39 UTC, daveoconnor commented
When running tilt up I was getting build errors related to uv and requirements.txt, which are most likely unrelated to this change.

Once that's fixed the Dockerfiles should probably benefit from be updated to use `localhost:5001` based images 
e.g. 
`FROM localhost:5001/python:3.12-slim as build`

`     Building image
     [background] read source files 91.47kB [done: 372ms]
     [build 1/9] FROM docker.io/library/python:3.12-slim
     [stage-1 5/9] RUN adduser --system --no-create-home django [cached]
     [stage-1 4/9] RUN apt-get update     && apt-get install --no-install-recommends -y     ca-certificates     curl     gettext     gnupg     && curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -     && echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list     && apt-get update     && apt-get install --no-install-recommends -y     libpq5     $(if [ "yes" = "yes" ]; then echo 'bash postgresql-client-16'; fi)     && apt-get install -y     awscli     && apt-get remove -y     curl     gnupg     && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* [cached]
     [stage-1 3/9] RUN set -x     && mkdir -p /usr/share/man/man1     && mkdir -p /usr/share/man/man7 [cached]
     [stage-1 2/9] WORKDIR /app/src [cached]
     [build 6/9] COPY requirements /tmp/requirements [cached]
     [build 5/9] RUN uv pip --no-cache install --upgrade setuptools wheel [cached]
     [build 4/9] RUN pip --no-cache-dir install --upgrade uv [cached]
     [build 3/9] RUN set -x     && python3 -m venv /app [cached]
     [build 2/9] RUN apt-get update     && apt-get install --no-install-recommends -y     build-essential     ca-certificates     curl     gettext     gnupg     && curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -     && echo "deb http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list     && apt-get update     && apt-get install --no-install-recommends -y     libffi-dev     libpq-dev     libssl-dev     postgresql-client-16     postgresql-client-common [cached]
     [build 7/9] RUN set -x     && if [ "yes" = "yes" ]; then uv pip --no-cache install -r /tmp/requirements/local.txt; fi
       → + [ yes = yes ]
       → + uv pip --no-cache install -r /tmp/requirements/local.txt
       → error: File not found: `/tmp/requirements/local.txt`
     
     ERROR IN: [build 7/9] RUN set -x     && if [ "yes" = "yes" ]; then uv pip --no-cache install -r /tmp/requirements/local.txt; fi

Build Failed: ImageBuild: process "/bin/sh -c set -x     && if [ \"$DEVEL\" = \"yes\" ]; then uv pip --no-cache install -r /tmp/requirements/local.txt; fi" did not complete successfully: exit code: 2
`

2024-09-18 08:02 UTC, rochecompaan requested changes

2024-09-18 08:02 UTC, rochecompaan commented on {{cookiecutter.project_slug}}/backend/Dockerfile
> +FROM localhost:5001/python:3.12-slim as build
Please don't hardcode the local registry in the Dockerfile. This leaves us with a Dockerfile that is not portable to different environment and it won't build in CI.

2024-09-18 17:56 UTC, daveoconnor commented
Also added to the ticket:

I've tried using `default_registry` to set the registry for pulled images but I wasn't seeing any speed improvement on them with a cluster tear down and rebuild.

Looking at the docs it seems like it's only for built images, and won't work for pulled images.

>  Specifies that any images that Tilt builds should be renamed so that they have the specified Docker registry. 

kustomization.yaml changes for the Deployments looks like it's the way to go again.

2024-09-19 13:55 UTC, rehan892 approved these changes

2024-09-19 14:11 UTC, rochecompaan approved these changes

2024-09-19 14:27 UTC, merged